# Generated by Django 3.2.7 on 2021-09-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('rate_name',), 'verbose_name': 'Валюта', 'verbose_name_plural': 'Курс валют'},
        ),
    ]
